import { Inter } from "next/font/google"
import "./globals.css"
import Navbar from "./Navbar"
import { AuthProvider } from "@/context/AuthContext"
import { ToastContainer } from "react-toastify"
import Footer from "./Footer"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "AppName",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="dark">
      <AuthProvider>
        <body className={`${inter.className} min-h-screen h-screen`}>
          <ToastContainer />
          <Navbar />
          {children}
          <Footer />
        </body>
      </AuthProvider>
    </html>
  )
}
